username: bajdcc
baseurl: /blog
markdown: redcarpet
safe: false
highlighter: pygments
title: bajdcc's blog
description: Programming is life
theme: slate
disqusname: bajdcc

# theme can be: hack, leep-day, merlot, midnight, minimal, modernist, slate, time-machine
# those themes are all come from GitHub Pages Themes
